### ISSUE TITLE
Hanging punctuation CSS 属性不生效

### ISSUE THREAD

**Issue by MrXCQ** [dookbook/dookbook-doc-webfrontend#236]
Hanging punctuation 能否在Chrome 浏览器上正常使用，有没有思路。谢谢！

**Comment by leven-cn** [comment]
@MrXCQ `hanging-punctuation`属性在当前主流浏览器中都没有实现，根据CSS规范定义，`text-indent`为负值时可达到类似效果，可作为不支持`hanging-punctuation`属性的备选方案。

**Comment by MrXCQ** [comment]
text-indent 在段落首行产生缩进效果，能否在段落内每一行产生与 Hanging punctuation 一样的效果呢？

**Comment by leven-cn** [comment]
段落`<p>`的文本就是一行，除非`<br>`强制换行。段落内的每一行可否理解成多个`<p>`还是`<p>`内强制换行，又或者因为容器宽度而换行？是指哪种情况？

**Comment by MrXCQ** [comment]
万分感谢您耐心的回复与解答。
目前是因为容器的宽度是固定的，<p> 段落内容会分成多行，这样形成的多行文字能否 达到hanging-punctuation 产生的效果。下图是hanging-punctuation 属性在Safari 显示效果，Chrome能否达到此效果。
![图片](https://user-images.githubusercontent.com/15794342/76507045-0ece8700-6487-11ea-932b-53bab0175d1d.png)

**Comment by leven-cn** [comment]
目前Chrome没有更好的方式实现
